name: Continuous Integration

on:
  pull_request:
    branches: 
      - develop
  push:
    branches: 
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12.1
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-elixir@v1
      with:
        otp-version: 22.2.1
        elixir-version: 1.10.0
    - name: Setup STRIPE_SECRET environment variable
      run: export STRIPE_SECRET="sk_test_123"
    - name: Setup STRIPE_HTTP_SECRET environment variable
      run: export STRIPE_HTTP_SECRET="secret"
    - name: Setup MIX_ENV environment variable
      run: export MIX_ENV="test"
    - name: Get dependencies
      run: mix deps.get
    - run: mix credo
    - run: mix dialyzer
    - run: mix test --cover
