name: Continuous Integration

on:
  pull_request:
    branches: 
      - develop
  push:
    branches: 
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12.1
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.2.1
          elixir-version: 1.9.4
      - name: Run checks
        env:
          STRIPE_SECRET: "sk_test_123"
          STRIPE_HTTP_SECRET: "secret"
          MIX_ENV: "test"
        run: |
          mix deps.get
          mix ecto.create
          mix ecto.migrate
          mix credo
          mix test --cover
